python amc_searchPPO.py \
    --job=train \
    --model=/home/lisiqi/amc-LLM/model/llama-2-7b-hf \
    --model_name=llama-2-7b-hf\
    --preserve_ratio=0.3 \
    --prune=para \
    --lbound=0.15 \
    --rbound=0.5 \
    --n_samples=64\
    --num_collect=15\
    --learning_epoch=10\
    --use_real_val \
    --acc_metric=acc1 \
    --reward=reward_benchmark \
    --train_episode=3000 \
    --seed=2024\
    --export_path=./checkpoints/llama1-7b_piqa_export.pth.tar
